DROP TABLE IF EXISTS `UME_USER` ;
CREATE TABLE `UME_USER` (
    `USER_ID` VARCHAR(16) BINARY NOT NULL	 COMMENT '用户识别ID',
    `USER_NAME` VARCHAR(64) BINARY 	 COMMENT '用户名称',
    `USER_PASSWORD` VARCHAR(64) BINARY 	 COMMENT '用户登录密码',
    `USER_MOBILE` VARCHAR(16) BINARY 	 COMMENT '用户手机',
    `USER_MOBILE_BAK` VARCHAR(16) BINARY 	 COMMENT '用户备用手机',
    `USER_IDENTITY_CARD` VARCHAR(32) BINARY 	 COMMENT '用户身份证号',
    `USER_DRIVE_LICENSE` VARCHAR(32) BINARY 	 COMMENT '用户驾驶证号',
    `USER_PASSPORT` VARCHAR(32) BINARY 	 COMMENT '用户护照号',
    `USER_ADDRESS` VARCHAR(256) BINARY 	 COMMENT '用户地址',
    `USER_EMAIL` VARCHAR(64) BINARY 	 COMMENT '用户邮箱',
    `USER_EMAIL_BAK` VARCHAR(64) BINARY 	 COMMENT '用户备用邮箱',
    `USER_LEVEL` INT(8) 	 COMMENT '用户等级',
    `USER_STATUS` INT(2) 	 COMMENT '用户账户状态',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'EM用户表' ;
ALTER TABLE `UME_USER` ADD CONSTRAINT `PK_UME_USER` PRIMARY KEY ( USER_ID ) ;

DROP TABLE IF EXISTS `UME_ROLE` ;
CREATE TABLE `UME_ROLE` (
    `ROLE_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '角色ID',
    `ROLE_NAME` VARCHAR(64) BINARY 	 COMMENT '角色名称',
    `ROLE_DESC` VARCHAR(128) BINARY 	 COMMENT '角色描述',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'EM角色定义表' ;
ALTER TABLE `UME_ROLE` ADD CONSTRAINT `PK_UME_ROLE` PRIMARY KEY ( ROLE_ID ) ;

DROP TABLE IF EXISTS `UME_USER_ROLE` ;
CREATE TABLE `UME_USER_ROLE` (
    `USER_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '用户ID',
    `ROLE_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '用户持有角色ID',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'EM用户角色分配表' ;
ALTER TABLE `UME_USER_ROLE` ADD CONSTRAINT `PK_UME_USER_ROLE` PRIMARY KEY ( USER_ID ,ROLE_ID ) ;

DROP TABLE IF EXISTS `UME_RESOURCE` ;
CREATE TABLE `UME_RESOURCE` (
    `RES_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '资源ID',
    `RES_TYPE` INT(2) NOT NULL	 COMMENT '资源类型',
    `RES_NAME` VARCHAR(64) BINARY 	 COMMENT '资源名称',
    `RES_GROUP` VARCHAR(64) BINARY 	 COMMENT '资源分组',
    `RES_LINK` VARCHAR(1024) BINARY 	 COMMENT '资源链接',
    `RES_INDEX` INT(8) 	 COMMENT '资源排序序号',
    `RES_STATUS` INT(1) 	 COMMENT '资源状态',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'EM资源管理表' ;
ALTER TABLE `UME_RESOURCE` ADD CONSTRAINT `PK_UME_RESOURCE` PRIMARY KEY ( RES_ID ,RES_TYPE ) ;

DROP TABLE IF EXISTS `UME_ROLE_ACL` ;
CREATE TABLE `UME_ROLE_ACL` (
    `ROLE_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '角色ID',
    `ACC_RES_ID` VARCHAR(32) BINARY NOT NULL	 COMMENT '角色可访问的资源ID',
    `ACC_RES_TYPE` INT(2) NOT NULL	 COMMENT '角色可访问的资源ID',
    `ACC_LEVEL` INT(2) NOT NULL	DEFAULT 1 COMMENT '访问级别',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT 'EM角色访问控制表' ;
ALTER TABLE `UME_ROLE_ACL` ADD CONSTRAINT `PK_UME_ROLE_ACL` PRIMARY KEY ( ROLE_ID ,ACC_RES_ID ,ACC_RES_TYPE ,ACC_LEVEL ) ;



